/**
 * Generated by scripts/generate-assets.js. Do not edit by hand.
 *
 * SVGs become React components via the Metro transformer. Use `currentColor`
 * for fills so AppIcon's `color` prop drives them from the theme rather than
 * baking a colour into the asset.
 */
export { default as HeartIcon } from './heart.svg';
export { default as StarIcon } from './star.svg';
