#!/usr/bin/env node
/**
 * Regenerate the asset barrels from the filesystem.
 *
 * Registering an asset by hand means editing a barrel every time one is
 * added, which is the kind of step that gets forgotten and then fails at
 * runtime with an undefined component. The directory is the source of truth;
 * this makes the barrel match it.
 *
 *   npm run assets
 *   npm run assets -- --check     # fail if the barrels are stale (for CI)
 *
 * SVGs become React components through the Metro transformer configured in
 * metro.config.js. PNGs and JPEGs become require() handles, which Metro
 * resolves at build time -- a dynamic require(`./${name}.png`) does not work
 * in React Native, which is why they are enumerated here.
 */
const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.join('src', 'assets');

/** `arrow-left.svg` -> `ArrowLeftIcon`; `logo-dark.png` -> `logoDark`. */
const toPascalCase = name =>
  name
    .replace(/\.[^.]+$/, '')
    .split(/[-_\s]+/)
    .filter(Boolean)
    .map(part => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');

const toCamelCase = name => {
  const pascal = toPascalCase(name);
  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
};

/**
 * `heart.svg` -> `HeartIcon`, but `lockIcon.svg` -> `LockIcon`, not
 * `LockIconIcon`. Both naming styles are in use in the wild and neither is
 * wrong, so the suffix is added only when it is missing.
 */
const toIconExport = file => {
  const pascal = toPascalCase(file);
  return pascal.endsWith('Icon') ? pascal : `${pascal}Icon`;
};

const listFiles = (dir, extensions) => {
  if (!fs.existsSync(dir)) return [];

  return fs
    .readdirSync(dir)
    .filter(file => extensions.includes(path.extname(file).toLowerCase()))
    .sort();
};

const buildIconBarrel = files => {
  if (files.length === 0) {
    return `/**
 * Generated by scripts/generate-assets.js. Do not edit by hand.
 *
 * No SVGs found in src/assets/icons. Drop one in and run \`npm run assets\`.
 */
export {};
`;
  }

  const exports = files
    .map(
      file => `export { default as ${toIconExport(file)} } from './${file}';`,
    )
    .join('\n');

  return `/**
 * Generated by scripts/generate-assets.js. Do not edit by hand.
 *
 * SVGs become React components via the Metro transformer. Use \`currentColor\`
 * for fills so AppIcon's \`color\` prop drives them from the theme rather than
 * baking a colour into the asset.
 */
${exports}
`;
};

const buildImageBarrel = files => {
  if (files.length === 0) {
    return `/**
 * Generated by scripts/generate-assets.js. Do not edit by hand.
 *
 * No raster images found in src/assets/images.
 */
export const images = {} as const;

export type ImageName = never;
`;
  }

  const entries = files
    .map(file => `  ${toCamelCase(file)}: require('./${file}'),`)
    .join('\n');

  return `/**
 * Generated by scripts/generate-assets.js. Do not edit by hand.
 *
 * Enumerated rather than resolved dynamically: Metro resolves require() at
 * build time, so require(\`./\${name}.png\`) does not work in React Native.
 *
 * @2x and @3x variants are picked by React Native automatically and must not
 * be listed separately.
 */
export const images = {
${entries}
} as const;

export type ImageName = keyof typeof images;
`;
};

const write = (file, content, check) => {
  const existing = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null;

  if (existing === content) {
    console.log(`  unchanged  ${file}`);
    return true;
  }

  if (check) {
    console.error(`  STALE      ${file}`);
    return false;
  }

  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, content);
  console.log(`  written    ${file}`);
  return true;
};

const assertNoCollisions = (files, toName, dir) => {
  const byName = new Map();

  for (const file of files) {
    const name = toName(file);
    byName.set(name, [...(byName.get(name) ?? []), file]);
  }

  const clashes = [...byName.entries()].filter(([, group]) => group.length > 1);

  if (clashes.length === 0) return;

  console.error(`\n  Two files in ${dir} produce the same export name:\n`);
  for (const [name, group] of clashes) {
    console.error(`      ${group.join(', ')}  ->  ${name}`);
  }
  console.error('\n  Rename one of them.\n');
  process.exit(1);
};

const main = () => {
  const check = process.argv.includes('--check');

  // @2x and @3x are density variants of an asset already listed, so including
  // them would produce duplicate keys that shadow each other.
  const iconFiles = listFiles(path.join(ROOT, 'icons'), ['.svg']);
  const imageFiles = listFiles(path.join(ROOT, 'images'), [
    '.png',
    '.jpg',
    '.jpeg',
    '.webp',
    '.gif',
  ]).filter(file => !/@[23]x\./.test(file));

  // Two files can reduce to one export name -- lock.svg and lockIcon.svg both
  // become LockIcon. Duplicate named exports are a SyntaxError that surfaces
  // from a generated file, where it reads as a bug in this script rather than
  // as two files that need distinct names.
  assertNoCollisions(iconFiles, toIconExport, 'src/assets/icons');
  assertNoCollisions(imageFiles, toCamelCase, 'src/assets/images');

  console.log(
    `\n  ${check ? 'Checking' : 'Generating'} asset barrels: ` +
      `${iconFiles.length} icon(s), ${imageFiles.length} image(s)\n`,
  );

  const results = [
    write(
      path.join(ROOT, 'icons', 'index.ts'),
      buildIconBarrel(iconFiles),
      check,
    ),
    write(
      path.join(ROOT, 'images', 'index.ts'),
      buildImageBarrel(imageFiles),
      check,
    ),
  ];

  if (results.includes(false)) {
    console.error('\n  Asset barrels are out of date. Run `npm run assets`.\n');
    process.exit(1);
  }

  console.log('');
};

main();
